#!/bin/bash

if [[ ! -z "$DOKKU_DEV" ]]; then
  export DOKKU_DEV=true
  export DOKKU_ROOT=/home/dokku

  chmod +x commands
  chmod +x install
  chmod +x dockerfiles/bin/manage

  ./commands mongodb:stop

  docker rmi ohardy/mongodb
  rm -rf /home/dokku/.o_mongodb
  docker build --no-cache -t ohardy/mongodb dockerfiles/

  ./install
fi
